
var poemas = [
    {
        title: "Voo" ,
        text: [
            'Cada vez que sinto',
            'o leve toque da liberdade',
            'em minha alma sedenta',
            'no voo da imaginação',
            'minhas mãos são como',
            'duas asas soltas',
            'riscando o meu céu',
            'um pedaço de papel'
        ],
        author: "Silvânia Guimarães",
    },
    {
        title: "Um Dia",
        text:[
            'Um dia num canto de Minas',
            'quero plantar sementes, percorrer terras, beber água',
            'na fonte e contemplar o horizonte',
            'Quero roer a raiz que os índios plantaram, e rezar ',
            'com os padres que nos ensinaram',
            'Andar à pé, de pé no chão, como essa gente humilde',
            'sofrida, que faz história',
            'Sugar com força cada pedaço de ar de cada folha',
            'que houver, pra dentro do meu peito',
            'Respirar amor, ar puro, ar verde',
            'Um dia, num canto de Minas',
            'quero esquecer o barulho dessas cidades gigantes e',
            'absorver a quietude de uma rocinha plantada entre',
            'árvores nativas, ao som de cascatas, correntes e límpidas',
            'com pássaros livres cantando além dos ares.',
            'Ouvir o vento sibilando uma canção qualquer.',
            'E de forma misteriosa, aquietar o espírito, para me',
            'libertar de tudo que nos prende em confusão nessa',
            'corrente feita de gente buscando sem nunca alcançar',
            'que procura sem encontrar, corre sem nunca chegar',
            'e, que, sem se alegrar, sorri; sente e não ama',
            'ambora ame sem sentir que ama.',
            'Um dia, num canto de Minas',
            'quero um encontro com a vida que há, prodigiosamente',
            'sem intenções. E em tudo, quero cantar.',
            'Um dia, num canto de Minas'
        ],        
        author: "Silvânia Guimarães",
    },
    {
        title: "Mosaico",
        text:[
            'Hoje sou o resultado',
            'de todas as vezes que caí e me quebrei',
            'como boneca de louça.',
            'Fragmentos colados',
            'de tudo que fui, de tudo que sou',
            'ou desejava ser.',
            'Talvez mostre algum remendo.',
            'pois não sei me maquilar.',
            'Sei juntar, colar, remendar como ninguém.',
            'Afinal, não é assim que se vive?',
            'Aos pedaços de cada dia?',
            'Afinal, quem nunca se perdeu,',
            'nem sofreu sequer uma vez na vida?',
            'Sim. A vida é feita de preciosos pedaços',
            'que vamos colando indefinidamente.',
            'Como num quebra-cabeças,',
            'assim vou me fazendo, desfazendo,',
            'refazendo como um enigma',
            'ou mosaico de espelhos'
        ],
        author: "Silvânia Guimarães",
    },
    {
        title: "Poema à Toa",
        text: [
            'Um dia um anjo branco me disse:',
            '-Vai-te embora alma humana!',
            'Vai viver vida mundana.',
            '',
            'Eu não suspeitava que nada sabia',
            'Pensava sim, em nascer e crescer',
            'Nada sabia sobre o viver',
            '',
            'Porque viver não é só,',
            'E simplesmente respirar',
            'Viver meu amigo, é lutar',
            '',
            'Hoje nesse mundo: vasto ringue',
            'Vejo gente cheia de vida,',
            'Vejo gente entristecida',
            '',
            'Pessoas vivendo no luxo',
            'Gente embaixo da ponte',
            'Alguém buscando uma fonte',
            '',
            'Carros cheios de vidas',
            'Que nas estradas da vida passam',
            'E a carcaça humana amassam',
            '',
            'Pessoa atrás dos óculos',
            'Das mesas, atrás das portas.',
            'Nos campos, as flores mortas...',
            '',
            'Morrem as flores os homens,',
            'Morrem todos os bichos',
            'Das poluições, dos lixos',
            '',
            'Morrem de assassínio, de desgosto',
            'De tristeza, morrem de alegria.',
            'Morrem mesmo de fobia',
            '',
            'Morrem loucos, bravos, suicidas',
            'Morrem de velhos à meia idade',
            'Os abortados sem ver a claridade',
            '',
            'E morre gente sem parar',
            'É  morte e dia, é morte e noite',
            'Morrem na lida: forjado açoite',
            '',
            'Mas triste, é quem morre a cada dia',
            'De fome em cada momento',
            'De frio lá no relento',
            '',
            'Triste é quem morre aos pouquinhos',
            'Lutando prá sobreviver',
            'Morrendo de tanto sofrer',
            '',
            'Outros morrem buscando o sol',
            'Pelas frestas de cada prédio',
            'Monstros frios do nosso tédio',
            '',
            'E PELA FALTA DE AMOR',
            'MEU DEUS! EU NÃO SABIA',
            'QUE SE MORRE TODO DIA.',
            '',
            'E eu me pergunto acaso',
            'Porque tão dispersa essa gente',
            'Como elos soltos duma mesma corrente?',
            '',
            'Prá quê meu Deus! Tanto vidro,',
            'Tanto ferro, tanto cimento',
            'Se a gente só vive um momento?',
            '',
            'Prá quê meu Deus, matar o bicho, o homem',
            'Prá quê tanta distância',
            'Calculada por quilômetros ganância?',
            '',
            'Prá quê matar o verde',
            'Deixando tudo escuro',
            'Tornando o ar impuro?',
            '',
            'Prá quê tanta fumaça, tanta sujeira, tanto mal',
            'Dentro e fora de nós',
            'Se nunca vivemos sós?',
            '',
            'Vamos parar com isso',
            'Vamos parar agora',
            'Vamos que já é hora',
            '',
            'De toda essa gente assumir',
            'Seu papel mais sério e profundo',
            'De transformador do mundo.',
        ],
        author: "Silvânia Guimarães",
    },
    {
        title: "Por Tudo que Há",
        text: [
            'Pela vida ou pela morte',
            'Que em cada corpo há',
            'Pela angústia ou pela sorte',
            'Que havemos de passá',
            '',
            'Nas melodias chorosas', 
            'Do canto de um sabiá',
            'Ou pelas noites saudosas',
            'Que o violeiro cantá',
            '',    
            'Pela taça de alegrias',
            'Da flor de maracujá',
            'Ou pela tristeza dos dias',
            'Em que cada rosa murchá',
            '',
            'Pelas rosas, pelos lírios',
            'Nos campos ao vento a bailá',
            'Pelos anseios e delírios',
            'Dessa gente toda a sonhá',
            '',
            'Pela criança singela',
            'Que o nosso futuro será',
            'Também pela moça mais bela',
            'E também pela sinhá',
            '',
            'Pelo tempo passado vivido',
            'Pelo amanhã que virá',
            'Pelo rosto de rugas sofrido',
            'Que o tempo desenha a bricá',
            '',
            'Pela ausência da doce imagem',
            'De alguém a sorte a buscá',
            'Pelo desenho na paisagem',
            'De dois olhos sem vida a se olhá',
            '',
            'Pelas flores mais graciosas',
            'Que o homem é capaz de plantá',
            'E cuidar com mãos generosas',
            'Pelas matas que o homem matá',
            '',
            'Pelos peixes que vivem nadando',
            'E os bichos no campo a pulá',
            'Pelas borboletas em bando',
            'E as aves do céu a voá',
            '',
            'Por todas as marcas que deixa',
            'A dor da ferida a sangrá',
            'Pela dura maldade ou a queixa',
            'Que em cada partida haverá',
            '',
            'Pela alegria que encerra',
            'O encontro de dois a se amá',
            'E mais por qualquer espera',
            'Em que os dois vive a sonhá',
            '',
            'Pelo milagre da fonte',
            'Da terra sempre a brotá',
            'Descendo feliz o monte',
            'Na terra a vida a jorrá',
            '',
            'Pelo sol já alto e pleno',
            'Por todo dia a raiá',
            'Pela estrela e seu aceno',
            'Pelas noites a brilhá',
            '',
            'Pelas noites e dias sem fim',
            'Pelo sol e lua a clareá',
            'Por todo o mundo enfim',
            'E tudo que nele há',
            '',
            'Que tudo seja alegria',
            'O que nesse mundo passá',
            'Que eu seja feliz todo dia',
            'Enquanto esse amor durá.',

        ],
        author: "Silvânia Guimarães",
    },
    {
        title: "Colcha de Retalhos",
        text: [
            'Persigo o som de uma serenata',
            'há muito perdida',
            'no tempo',
            'e que me diz para voltar,',
            'juntar meus pedaços',
            'com medo e coragem.',
            'Pela metade do copo',
            'Misturo o pó ao presente.',
            'Busco meu passado.',
            'Cato cacos improváveis',
            'de versos e canções,',
            'porque a lembrança sobrevive',
            'à saudade, à nostalgia,',
            'à modernidade.',
            'Relembro os cheiros, os sabores,',
            'os sons de outros tempos,',
            'os risos e os cantos.',
            'E na pauta da noite',
            'alinhavo os pedaços',
            'da minha história.',
            'Faço e refaço a minha colcha',
            '                    de retalhos'
        ],
        author: "Silvânia Guimarães",
    },
    {
        title: "Clamor",
        text: [
            'Elevo minhas mãos para o alto.',
            'Meus olhos miram o infinito.',
            'Minhas pernas ensaiam um salto.',
            'Minha boca ameaça um grito.',
            '',
            'Meus dedos na areia da praia',
            'esboçam uma palavra estranha.',
            'É a ideia que a mente ensaia',
            'sagrado nome que desentranha.',
            '',
            'Abro meu peito ao sol.',
            'Durmo meu corpo à lua.',
            'Meus pés caminham na rua.',
            '',
            'E tudo o que vive em mim',
            'por você clama e espera.',
            'Ó Senhor! Senhor dessa quimera.'
        ],
        author: "Silvânia Guimarães",
    },
    {
        title: "Declaração",
        text: [
            'Definitivamente',
            'não é em nenhum rio que deposito meu suor',
            'e minhas lágrimas incontidas.',
            'Não é o mar que colhe os cristais de minhas ilusões,',
            'mas as dobras de minha alma.',
            'Meu tempo. Em tudo, sempre',
            'meu espírito pulsando minha vida em teu nome,',
            'em teu favor, em teu sabor',
            'vejo a vida pela luz dos olhos.',
            'E o que é a vida senão estar só',
            'em meio a tanta gente?',
            'Senão o trabalho, o estudo, a ilusão?',
            'O que é senão a fome de toda essa gente?',
            'Fome de poder, de comida, de justiça;',
            'alguém querendo amor?',
            'E essa vontade de chegar, não se sabe aonde,',
            'caminhar sem saber por onde?',
            'E o chão se abre.',
            'Onde estou? Onde estamos nós nessa busca sem fé?',
            'Choramos partidas, buscamos chegadas.',
            'Mas a vida é muito mais:',
            'é caminhada, é encontro, é pensar em alguém.',
            'É ver a vida através dos olhos de outrem.',
            'É querer bem'
        ],
        author: "Silvânia Guimarães",
    },
    {
        title: "Sina",
        text: [
            'Às vezes o mundo me aborrece',
            'e eu choro e rezo.',
            'Às vezes o mundo me entristece',
            'e eu choro e escrevo.',
            'Sofrimento ou alívio,',
            'o mundo me atormenta.',
            'Relógio sem ponteiro.',
            'Benção ou castigo.',
            'Escrevo para dizer',
            '(sem ninguém saber).',
            'Para chorar',
            '(sem ninguém ver).',
            'Escrevo para assumir e mostrar',
            'até mesmo para disfarçar',
            'o que o mundo me faz',
            'cumprindo a minha sina.'
        ],
        author: "Silvânia Guimarães",
    },
    {
        title: "Palavras",
        text: [
            'As palavras certas?',
            'Eu nunca as encontrei.',
            'Encontrei outras',
            'incertas',
            'E as escrevi',
            'imperfeitas',
            'indescritíveis.',
            'Ainda assim insisti',
            'persisti',
            'Mas com a palavra certa',
            'a rima perfeita',
            'eu quero um encontro marcado.'
        ],
        author: "Silvânia Guimarães",
    },
    {
        title: "Eu",
        text: [
            'Sou composta por urgências:',
            'minhas alegrias são intensas;',
            'minhas tristezas, absolutas.',
            'Entupo-me de ausências,',
            'Esvazio-me de excessos.',
            'Eu não caibo no estreito,',
            'eu só vivo nos extremos.',
            '',
            'Pouco não me serve,',
            'médio não me satisfaz,',
            'metades nunca foram meu forte!',
            '',
            'Todos os grandes e pequenos momentos,',
            'feitos com amor e com carinho,',
            'são pra mim recordações eternas.',
            'Palavras até me conquistam temporariamente…',
            'Mas atitudes me perdem ou me ganham para sempre.',
            '',
            'Suponho que me entender',
            'não é uma questão de inteligência',
            'e sim de sentir,',
            'de entrar em contato…',
            'Ou toca, ou não toca'
        ],
        author: "Clarice Lispector",
    }

  
]

export default poemas;